#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""voice-agent - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text and Text-to-Speech)
- Groq (LLM)

Run the bot using::

    uv run bot.py
"""

import os

import aiohttp
from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.audio.vad.vad_analyzer import VADParams
from pipecat.frames.frames import TTSSpeakFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import RunnerArguments, WebSocketRunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.services.deepgram.tts import DeepgramTTSService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.websocket.fastapi import FastAPIWebsocketParams
from pipecat.workers.runner import WorkerRunner
from pydantic import BaseModel

import booking
from llm import build_llm
from prompt import build_system_instruction, greeting, reload_intake
from tools import get_tools

load_dotenv(override=True)


class CallInfo(BaseModel):
    """Caller details fetched from the Twilio REST API."""

    from_number: str | None = None
    to_number: str | None = None


async def get_call_info(call_sid: str | None) -> CallInfo | None:
    """Fetch call information from the Twilio REST API using aiohttp.

    Args:
        call_sid: The Twilio call SID (e.g. call_data.call_id), or None.

    Returns:
        A CallInfo with the caller's numbers, or None if it couldn't be fetched.
    """
    if not call_sid:
        return None

    account_sid = os.getenv("TWILIO_ACCOUNT_SID")
    auth_token = os.getenv("TWILIO_AUTH_TOKEN")

    if not account_sid or not auth_token:
        logger.warning("Missing Twilio credentials, cannot fetch call info")
        return None

    url = f"https://api.twilio.com/2010-04-01/Accounts/{account_sid}/Calls/{call_sid}.json"

    try:
        # Use HTTP Basic Auth with aiohttp
        auth = aiohttp.BasicAuth(account_sid, auth_token)

        async with aiohttp.ClientSession() as session:
            async with session.get(url, auth=auth) as response:
                if response.status != 200:
                    error_text = await response.text()
                    logger.error(f"Twilio API error ({response.status}): {error_text}")
                    return None

                data = await response.json()

                return CallInfo(from_number=data.get("from"), to_number=data.get("to"))

    except Exception as e:
        logger.error(f"Error fetching call info from Twilio: {e}")
        return None


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
    """
    logger.info("Starting bot")

    # Speech-to-Text service
    stt = DeepgramSTTService(api_key=os.getenv("DEEPGRAM_API_KEY"))

    # Text-to-Speech service (Deepgram Aura-2, streamed over websocket; same key as STT)
    tts = DeepgramTTSService(
        api_key=os.getenv("DEEPGRAM_API_KEY"),
        settings=DeepgramTTSService.Settings(
            voice=os.getenv("DEEPGRAM_VOICE", "aura-2-helena-en"),
        ),
    )

    # LLM with provider failover (see llm.py; order set by LLM_ORDER in .env). The system
    # instruction (persona, rules, client document) is rebuilt per session so document
    # edits and today's date are always current.
    reload_intake()
    llm = build_llm(build_system_instruction(booking_enabled=booking.is_configured()))

    # Tools listed here register with the LLM automatically.
    context = LLMContext(tools=get_tools())
    # stop_secs: silence needed before the agent treats the user's turn as finished.
    # Pipecat's default of 0.2s cuts people off mid-thought; ~0.6s feels natural.
    vad = SileroVADAnalyzer(params=VADParams(stop_secs=float(os.getenv("VAD_STOP_SECS", "0.6"))))
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(vad_analyzer=vad),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    # Phone audio is 8 kHz, so run the whole pipeline at 8 kHz on calls to skip
    # resampling. The website keeps the default higher-quality rates.
    sample_rates = {}
    if isinstance(runner_args, WebSocketRunnerArguments):
        sample_rates = {"audio_in_sample_rate": 8000, "audio_out_sample_rate": 8000}

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
            **sample_rates,
        ),
    )

    runner = WorkerRunner(handle_sigint=runner_args.handle_sigint)

    await runner.add_workers(worker)

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")
        # A fixed greeting goes straight to TTS: no LLM round trip, so the caller hears
        # the company name immediately. It is also added to the context.
        await worker.queue_frames([TTSSpeakFrame(greeting())])

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await runner.cancel()

    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport_params = {
        "webrtc": lambda: TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        # create_transport sets the twilio serializer and add_wav_header automatically.
        "twilio": lambda: FastAPIWebsocketParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    }

    transport = await create_transport(runner_args, transport_params)

    # OPTIONAL personalization: create_transport parsed the Twilio websocket, so the
    # call data is on runner_args.call_data. Look up the caller via the Twilio REST API
    # to personalize the conversation (e.g. fetch customer info from your own backend).
    call_data = runner_args.call_data
    call_info = await get_call_info(call_data.call_id) if call_data else None
    if call_info:
        logger.info(f"Call from: {call_info.from_number} to: {call_info.to_number}")

    await run_bot(transport, runner_args)


def _mount_widget() -> None:
    """Serve the built website widget at /widget/ (demo page + voice-widget.js)."""
    from pathlib import Path

    from fastapi.staticfiles import StaticFiles
    from pipecat.runner.run import app

    dist = Path(__file__).resolve().parent.parent / "client" / "widget" / "dist"
    if dist.is_dir():
        app.mount("/widget", StaticFiles(directory=str(dist), html=True), name="widget")
        logger.info("Widget demo page: http://localhost:7860/widget/")
    else:
        logger.warning("Widget not built (run `npm run build` in client/widget); /widget disabled")


if __name__ == "__main__":
    from pipecat.runner.run import main

    _mount_widget()
    main()
